### ISSUE TITLE
アセンブリが動作しない

### ISSUE THREAD

**Issue by Comamoca** [Comamoca/Awesome-DDSK#15]
[アセンブリ](https://github.com/Comamoca/Awesome-DDSK/blob/329100c71e320afbdde439d6669f3698b38cef77/S/Chatyusha.s)が動かない不具合が起きています。

僕が考えつく限りの事を試して見ましたが、うまく実行できませんでした。
もし実行する方法がについて何かお知りならばコメントして下さると助かります。

**Comment by Chatyusha** [comment]
DockerfileとREADME.mdを追加しました。
そちらを見ていただけるとおそらく動くはずです。

**Comment by Comamoca** [comment]
ありがとうございます。確認します。

**Comment by Comamoca** [comment]
動作確認が終わりましたのでmergeしました。
このissueも閉じさせていただきます。

https://github.com/Comamoca/Awesome-DDSK/pull/20
