### ISSUE TITLE
C#の実行方法について

### ISSUE THREAD

**Issue by Comamoca** [Comamoca/Awesome-DDSK#26]
C#のDockerfileを作成する際に、C#についての実行方法が不明なためDockerfileを作成出来ません。

@Chatyusha 
C#のプログラムを作成した環境や実行方法について教えていただけるとありがたいです。

**Comment by Chatyusha** [comment]
遅くなってすみません。
C#のDockerfileとREADMEを書きました。

**Comment by Comamoca** [comment]
PRが来たのでこのissueは閉じさせていただきます。
